// let a = 3;
// let v = 3*a;
// console.log(v);
// let s = 6*a*2;
// console.log(s);
// let a = 3;
// let b = 3;
// let c = 3;
// let v = a*b*c;
// console.log(v);
// let s = 2*a*b+b*c+a*c;
// console.log(s);
// let p = 5;
// let r = 5;
// let l = 2*p*r;
// console.log(l);
// let s = p*r*r;
// console.log(s);
// let a = 5;
// let b = 5;
// let s = a+b/2;
// console.log(s);
// let a = 5;
// let b = 5;
// let s = a*b/0.5;
// console.log(s);
// let a = 5;
// let b = 5;
// let s = a+b;
// console.log(s);
// let v = a*b;
// console.log(v);
// let d = a*2;
// let g = b*2;
// console.log(d);
// console.log(g);
// let a = 5;
// let b = 5;
// let c = a*b*2/0.5;
// console.log(c);
// let p = a+b+c;
// console.log(p);
// let p = 3.14;
// let r = 3.14;
// let l = 2*p*r;
// console.log(l);
// let s = p*r*r;
// console.log(s);
// let x1 = 5;
// let x2 = 5;
// let d =  Math.abs(
//     x1-x2
// )
// console.log(d);
// let a = 5;
// let b = 5;
// let c = 5;
// let s = a+c;
// let d = b+c;
// let r = s+d;
// console.log(s);
// console.log(d);
// console.log(r);
//  let a = 5;
//  let b = 5;
//  let c = 5;
//  let r = a+c;
//  let e = b+c;
//  let p = r*e;
//  console.log(p);
// let a = 5;
// let b = 5;
// let c = 4;
// let d = 6;
// let y = a*b*c*d;
// let p = a+b+c+d;
// console.log(y);
// console.log(p);
// let x1 = 5;
// let y1 = 5;
// let x2 = 6;
// let y2 = 6;
// let d = Math.abs (
//     (x2-x1*2)+(y2-y1*2)
// )
// console.log(d);
// let x1 = 5;
// let y1 = 5;
// let x2 = 6;
// let y2 = 6;
// let x3 = 6;
// let y3 = 6;
// let a = ( ( x1-x2)**2 - (y2-y1)**2)**0.5;
// let b = ( ( x2-x3)**2 - (y1-y3)**2)**0.5;
// let c = ( ( x1-x3)**2 - (y2-y3)**2)**0.5;
// let s = a+b+c/2;
// console.log(s);
// let a = 5;
// let b = 2;
// let c = 8;
// a = b;
// b = c;
// c = a;
// console.log(a);
// console.log(b);
// console.log(c);
// let x = 5;
// let y = 3*x-6*x-7**2
// console.log(y);
// let a = 88;
// let a2 = a**2;
// let a4 = a**4;
// let a5 = a**5;
// console.log(a2);
// console.log(a4);
// console.log(a5);
// let a = 88;
// let a2 = a**2;
// let a4 = a**4;
// let a5 = a**5;
// let a10 = a**10;
// let a15 = a**15;
// console.log(a10 );
// console.log(a15);
// console.log(a2);
// console.log(a4);
// console.log(a5);
// let a = 380;
// let p = 0<a<360;
// console.log(p);
// let a = 5;
// let p = 5;
// let r = 0<a<2*p;
// console.log(r);
// let Tf = 5;
// let Tc = 5;
// let r = Tc =(Tf-32)*5/9;
// console.log(r);
// let x = 5;
// let a = 500;
// let k = x/5;
// let y = 15;
// let g = a*3;
// console.log(x);
// console.log(a);
// console.log(k);
// console.log(y);
//  console.log(g);
// let x = 5;
// let a = 100;
// let y = 10;
// let b = 150;
// let k = a/x;
// let g = b/y;
// let s = k-g;
// console.log(s);
// console.log(x);
// console.log(a);
// console.log(y);
// console.log(b);
// let a = 0;
// let b = 0;
// let x = 0;
// let s = a*x+b
// console.log(s);
